name: Deploy Pygbag to GitHub Pages

on:
  push:
    branches: ["main"] # Executa a cada push na branch main
  workflow_dispatch: # Permite executar manualmente pela aba Actions

jobs:
  build-pygbag:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para publicar na branch gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versão estável para o Pygbag

      - name: Install Pygbag
        run: python -m pip install pygbag

      - name: Build with Pygbag
        run: python -m pygbag --build main.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web
